prior:
  base_orientation: [-0.8530611, 0.0094068, -0.001849, 0.5217229] # [0.1896408,0,0,-0.9818535]  # yaw -2.76
  base_velocity: [0,0,0]
  base_position: [0,0,0]
  gyroscope_bias: [0,0,0]
  accelerometer_bias: [0,0,0]
  base_orientation_std: 0.1
  base_velocity_std: 0.1
  base_position_std: 0.001
  gyroscope_bias_std: 0.1
  accelerometer_bias_std: 0.1
  # landmarks: 
  #   - id: 0
  #     position: [1.0,1.0,0.0] 
  #   - id: 1
  #     position: [1.0,-1.0,0.0]
  #   - id: 2
  #     position: [2.0,0.0,1.0]